# Generated by Django 3.2.9 on 2021-12-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_multistepformmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='MultiStepFormModel',
        ),
    ]
