# Generated by Django 3.2.9 on 2021-12-12 13:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211211_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='about_us',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
