# Generated by Django 3.2.9 on 2021-12-02 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomadation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.CharField(choices=[('budget', 'budget'), ('mid range', 'mid range'), ('up market', 'up market')], max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cars')),
                ('category', models.CharField(choices=[('executive', 'executive'), ('4x4', '4x4'), ('safari', 'safari'), ('vans', 'vans'), ('salon', 'salon'), ('buses', 'buses'), ('pickups', 'pickups'), ('trucks', 'trucks')], max_length=50)),
                ('rating', models.FloatField(default=1.0)),
                ('capacity', models.PositiveIntegerField(default=3)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='flights')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='gallery')),
                ('category', models.CharField(choices=[('gallery', 'gallery'), ('partner', 'partner')], default='gallery', max_length=50)),
                ('caption', models.CharField(max_length=100, null=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('group', 'group'), ('custom', 'custom')], default='group', max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='package')),
                ('slots', models.PositiveIntegerField(default=0)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('arrival_accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_accom', to='myapp.accomadation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.packagecategory')),
                ('trip_accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_accom', to='myapp.accomadation')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('permit_class', models.CharField(default='DL', max_length=100)),
                ('permit', models.FileField(upload_to='permits')),
                ('photo', models.ImageField(upload_to='cars')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('trip', 'trip'), ('flight', 'flight'), ('car hire', 'car hire')], default='trip', max_length=50)),
                ('flight_type', models.CharField(choices=[('one way', 'one way'), ('return', 'return')], default='one way', max_length=30)),
                ('departure_date', models.DateField(max_length=100, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('telephone', models.CharField(max_length=20)),
                ('pickup', models.CharField(max_length=100)),
                ('dropoff', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('slots', models.PositiveIntegerField(default=0)),
                ('adults', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('infants', models.PositiveIntegerField(default=0)),
                ('driven_by', models.CharField(choices=[('driver', 'our driver'), ('self', 'self')], default='driver', max_length=40, null=True)),
                ('carhire_trip', models.CharField(choices=[('up country', 'up country'), ('town service', 'town service')], default='up country', max_length=100)),
                ('time_booked', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_booking', to='myapp.car')),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.flight')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.trip')),
            ],
            options={
                'ordering': ['-time_booked'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.packagecategory')),
            ],
        ),
    ]
