# Generated by Django 3.2.9 on 2021-12-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_accomodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_accom', to='myapp.accomadation'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_accomodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_accom', to='myapp.accomadation'),
        ),
    ]
