# Generated by Django 3.2.9 on 2021-12-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='category',
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(to='myapp.Category'),
        ),
    ]
