# Generated by Django 3.2.9 on 2021-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rating',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
