# Generated by Django 3.2.9 on 2021-12-10 10:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211210_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
