# Generated by Django 3.2.9 on 2021-12-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211210_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
