# Generated by Django 3.2.9 on 2021-12-11 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_auto_20211211_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_on']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='time_booked',
            new_name='booked_on',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
