# Generated by Django 3.2.9 on 2021-12-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20211211_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='carhire_trip',
            field=models.CharField(choices=[('up country', 'up country'), ('town', 'town')], default='up country', max_length=100),
        ),
    ]
