# Generated by Django 3.2.9 on 2021-12-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
